title: CHENG Laboratory of
subtitle: Epigenetics and Therapeutics in Immuno-Oncology
logo-text: true
header: #112f57
footer: images/footer.png
links:
  email: alfredlabmailing@gmail.com
  google-scholar: Alfred S.L. Cheng
  github: ACLab-Bioinfo
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: alfredlabmailing@gmail.com
github: ACLab-Bioinfo
instagram: ACLab-Bioinfo
youtube: ACLab-Bioinfo
