- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor sit amet_, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1126/scitranslmed.aaz6804
  type: paper
  description: test test
  date: 2021-4-7
  image: https://www.sbs.cuhk.edu.hk/enewsletter/2021vol11no2/_custom/image-slider/alfred-2.jpg
  tags:
    - Epigenomic
    - ICB

- id: doi:10.1136/gutjnl-2018-317257
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  date: 2020-1-7
  tags:
    - Epigenomic
    - Microenvironment

- id: doi:10.1136/gutjnl-2017-314032
  type: paper
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5961939/bin/nihms966563f1.jpg
  date: 2018-4-6