- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor sit amet_, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review


- id: doi:10.1016/j.ymthe.2022.09.012
  type: paper
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1525001622005664-fx1.jpg
  date: 2023-1-4

- id: doi:10.1021/acs.jmedchem.2c01132
  type: paper
  image: https://pubs.acs.org/cms/10.1021/acs.jmedchem.2c01132/asset/images/medium/jm2c01132_0026.gif
  date: 2022-11-30

- id: doi:10.1038/s41423-022-00872-3
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41423-022-00872-3/MediaObjects/41423_2022_872_Fig7_HTML.png
  date: 2022-5-20

- id: doi:10.1016/j.canlet.2021.10.039
  type: paper
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0304383521005553-gr1.jpg
  date: 2022-1-28

- id: doi:10.3390/cancers13102418
  type: review
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8156220/bin/cancers-13-02418-g001.jpg
  date: 2021-5-17

- id: doi:10.1126/scitranslmed.aaz6804
  type: paper
  description: test test
  date: 2021-4-7
  image: https://www.sbs.cuhk.edu.hk/enewsletter/2021vol11no2/_custom/image-slider/alfred-2.jpg
  tags:
    - Epigenomic
    - ICB

- id: doi:10.1038/s41423-020-00534-2
  type: paper
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8115036/bin/41423_2020_534_Fig6_HTML.jpg
  date: 2020-8-10

- id: doi:10.1136/gutjnl-2018-317257
  image: https://gut.bmj.com/content/gutjnl/69/2/365/F8.large.jpg
  date: 2020-1-7
  tags:
    - Epigenomic
    - Microenvironment

- id: doi:10.1038/s41467-019-11274-x
  type: paper
  image: images/research.img/Tianyuan_NC.jpg
  date: 2019-7-29

- id: doi:10.1038/s41467-018-08245-z
  type: paper
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-018-08245-z/MediaObjects/41467_2018_8245_Fig1_HTML.png?as=webp
  date: 2019-1-18

- id: doi:10.1101/gr.240036.118
  type: paper
  image: https://genome.cshlp.org/content/29/4/543/F1.medium.gif
  date: 2019-2-11

- id: doi:10.1038/s41467-018-07402-8
  type: paper
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-018-07402-8/MediaObjects/41467_2018_7402_Fig1_HTML.png?as=webp
  date: 2018-11-6

- id: doi:10.1136/gutjnl-2017-314032
  type: paper
  image: https://gut.bmj.com/content/gutjnl/67/5/931/F8.large.jpg
  date: 2018-4-6

